パーサーのリファクタ & 正規表現の最適化
tdu-historylog/web pull request #35
Opened 2021-04-26 16:52 UTC by fujiwaraizuho

close #34

2021-04-26 23:45 UTC, yuto51942 requested changes

2021-04-26 23:45 UTC, yuto51942 commented on utils/logUtil.ts
>  export function validateQrData(qrData: string): boolean {
同じ引数を持つ関数が複数あるのでクラス化した方が見栄えがいいと思います

2021-04-27 00:01 UTC, fujiwaraizuho commented on utils/logUtil.ts
>  export function validateQrData(qrData: string): boolean {
修正します

2021-04-27 07:38 UTC, yuto51942 approved these changes
LGTM

2021-04-27 07:46 UTC, merged