Fix/color and button position
tdu-historylog/web pull request #73
Opened 2021-05-04 05:41 UTC by yuto51942

#72 の続き

- テーマ変更を設定に移動
- 色の細かい調整

To. @Nekoya3 @fujiwaraizuho 
色の微調整しました。ご確認いただけたら幸いです。

<div>
<img src="https://user-images.githubusercontent.com/24271196/116964147-c525a900-ace5-11eb-94fb-38c1a6d70329.png" width="35%" />
<img src="https://user-images.githubusercontent.com/24271196/116964143-c35be580-ace5-11eb-8075-5e7dd8b7ce32.png" width="35%" />
</div>

2021-05-04 06:03 UTC, Nekoya3 approved these changes
LGTMです

2021-05-04 06:09 UTC, HIBIKI-CUBE commented
細かいですが、ダークモード切り替え時にロゴがチラつくのが気になりました。
SVGはimgじゃなくobjectで読み込めば、SVG内にスタイルを記述してダークモードで色切り替えできます。
もしくはSVGをインラインで記述すればCSSから直接コントロールもできます。
その分svgの再読み込み分の通信量が削減できます。

2021-05-04 06:13 UTC, Nekoya3 commented
next/ImageのImage Optimizationの関係ですね...
next-react-svgとか使ってインラインにしちゃっても良さそうです

2021-05-04 06:35 UTC, Nekoya3 commented
#74が対応案になりますー @yuto51942

2021-05-04 06:51 UTC, Nekoya3 approved these changes

2021-05-04 08:45 UTC, HIBIKI-CUBE commented
de5fd36 システムの設定に全く影響されなくなるのは想定通りの動作？？
読み込み後にダークモードを切り替えても全く反応しなくなる。
例えば、iPhoneなら読み込んだ後にコントロールセンターから明るさ調節のバーを長押ししてダークモードを切り替え。

2021-05-04 08:49 UTC, yuto51942 commented
@HIBIKI-CUBE 
テーマ情報をlocalstorageに保存しているのですが、再起動時にシステム依存のテーマに強制的に変更されてしまいます。
システムはダークモードだけど、logcationではライトモードで使いたい場合では起動時に毎回テーマを切り替える必要があったのでシステムの依存からは外しました。

2021-05-04 08:51 UTC, HIBIKI-CUBE commented
@yuto51942 
localstorageにテーマ情報がまだなければ、その時はシステムの設定に従った方が親切なのでは？

2021-05-04 08:56 UTC, Nekoya3 commented on utils/theme.ts
> +  initialColorMode: 'light',
```suggestion
  initialColorMode: 'system',
```

上で指摘されている問題、この変更で解決可能だと思われます

2021-05-04 08:57 UTC, Nekoya3 commented on utils/theme.ts
> +  initialColorMode: 'light',
問題はChakraUIの挙動的に２度目のアクセスからlocalstorageの値を利用してくれるかどうかが...

2021-05-04 08:57 UTC, yuto51942 commented on utils/theme.ts
> +  initialColorMode: 'light',
なんと、、、、！？！？！？

2021-05-04 08:58 UTC, Nekoya3 commented on utils/theme.ts
> +  initialColorMode: 'light',
ちょっと試してますのですこしお待ちを....

2021-05-04 09:08 UTC, Nekoya3 commented on utils/theme.ts
> +  initialColorMode: 'light',
今動作確認しましたが大丈夫そうですね...

実際の挙動としては
初回〜設定変更 : localstorageにデータを保存しない
設定変更 : localstorageにデータを保存
それ以降 : localstorageのデータを利用

2021-05-04 11:29 UTC, yuto51942 commented on utils/theme.ts
> +  initialColorMode: 'light',
@Nekoya3 Fork先でビルド失敗したので確認したところTypeでsystemは定義されていないようです。

https://github.com/chakra-ui/chakra-ui/blob/75edcf41e7ff4acc2569f2169949063c164d8f6e/packages/color-mode/src/color-mode.utils.ts#L8

2021-05-04 12:43 UTC, yuto51942 commented
@Nekoya3 @HIBIKI-CUBE 
initialテーマのsystem割当はThemeConfigではなく

```jsx
<ColorModeScript initialColorMode="system" />
```

で定義するようだったので変更しました。ビルド通るの確認しました。

2021-05-05 02:45 UTC, Nekoya3 requested changes
_documentと_appで同じスクリプト読んでるのが少し気になりました...!

2021-05-05 02:45 UTC, Nekoya3 commented on pages/_document.tsx
> +          <ColorModeScript initialColorMode={theme.config.initialColorMode} />
```suggestion
          <ColorModeScript initialColorMode={"system"} />
```

`pages/_app.tsx ` でもColorModeScriptを読んでるんですが、こっちを変えるべきかもしれないです

2021-05-05 02:45 UTC, Nekoya3 commented on pages/_app.tsx
> +    <ColorModeScript initialColorMode="system" />
```suggestion
```
`pages/_document.tsx ` でのsuggestを見てください

2021-05-05 02:45 UTC, Nekoya3 commented on pages/_app.tsx
> +import {ChakraProvider, ColorModeScript} from '@chakra-ui/react';
```suggestion
import {ChakraProvider} from '@chakra-ui/react';
```

2021-05-05 10:33 UTC, merged